version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - dbdata:/var/opt/mssql  
    environment:
      - SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=Y
    ports:
      - "51599:1433"
  
  rules-engine:
    build:
      context: .
      dockerfile: /host/JS.Abp.RulesEngine.Blazor.Server.Host/Dockerfile
    environment:
        - ASPNETCORE_URLS=http://0.0.0.0:80
        - ConnectionStrings__Default=Server=sqlserver;Database=RulesEngine_ModuleDb;Trusted_Connection=True;User=sa;Password=yourStrong(!)Password;Integrated Security=false
    depends_on:
      - sqlserver
    ports:
      - "51601:80"

volumes:
  dbdata: