version: '3.4'

services:
  sqlserver:
    environment:
      - SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=Y
    ports:
      - "51599:1433"

 
  rules-engine:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__Default=Server=sqlserver;Database=RulesEngine_ModuleDb;Trusted_Connection=True;User=sa;Password=yourStrong(!)Password;Integrated Security=false
    ports:
      - "51601:80"