version: '3.4'

services:
  migrations:
    build:
      context: .
      dockerfile: /database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - RulesEngine_DB=RulesEngine_ModuleDb
      - SA_PASSWORD=yourStrong(!)Password
